# Generated by Django 3.1.7 on 2021-05-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20210523_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='elec_status',
            field=models.TextField(choices=[('active', 'active'), ('pending', 'pending'), ('ended', 'ended')], default='pending'),
        ),
    ]
