# Generated by Django 3.1.7 on 2021-05-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210523_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummycitizeninfo',
            name='picture',
            field=models.FileField(default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
