# Generated by Django 3.1.7 on 2021-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210523_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummycitizeninfo',
            name='elec_Worker',
            field=models.BooleanField(default=False),
        ),
    ]
