# Generated by Django 3.1.7 on 2021-05-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_dummycitizeninfo_elec_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinfo',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidateinfo',
            name='candidate_info',
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='elec_name',
            field=models.CharField(default='', max_length=41),
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='nid',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
